### ISSUE TITLE
Use SilentChemObjectBuilder instead of DefaultChemObjectBuilder

### ISSUE THREAD

**Issue by OBrink** [OBrink/RanDepict#21]
This is nothing urgent, but CDK's SilentChemObjectBuilder is faster than the DefaultChemObjectBuilder.

**Comment by Kohulan** [comment]
How fast it is? Why do they have these two?

**Comment by OBrink** [comment]
According to @jonasschaub, the DefaultChemObjectBuilder throws events, while the SilentChemObjectBuilder does not do that and is on average up to 20% faster

**Comment by Kohulan** [comment]
Great Thanks :D
